# Generated by Django 4.1.7 on 2023-04-20 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_remove_passenger_flights_remove_reservation_flight_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='origin',
            new_name='orgin',
        ),
    ]
